### PR TITLE
Fix Triple Axel's base power boost

### PR DESCRIPTION
**Pull request by KrisXV**

### CODE REVIEW

**Comment by scheibo** [comment]
Thanks

**Comment by AustinXII** [comment]
Is this right? If the move hits twice the damage is going to be 40+40 and for 3 hits it’s going to be 60+60+60? I did 30 because 2 hits should be 40+20(30x2) and for three hits 60+40+30(40x3)

**Comment by AustinXII** [comment]
Although I am freshly out of surgery and on medications so forgive me if am wrong lol

**Comment by AustinXII** [comment]
You’re modifying the base power of each hit not the final power

**Comment by KrisXV** [comment]
Oh... I didn’t realize just HOW hacky this was

**Comment by AustinXII** [comment]
Should’ve went through with my more detailed comment to explain why it’s listed like this. Wasn’t expecting a sneaky revive from pre lol

**Pull request merged**
