### PR TITLE
Fix Punishment (gen 4)

### PR DESCRIPTION
**Pull request by tylerstanczak**
original basePower is 0 in moves data set... 
gen 5+ has solved this problem by hardcoding the 60 basePower in the calculation on line 191
copying gen 5+ solution for gen 4

### CODE REVIEW

**Comment by tylerstanczak** [comment]
Data for Miasmaw and Miasmite was taken from:
- https://www.smogon.com/dex/ss/pokemon/miasmaw/
- https://www.smogon.com/dex/ss/pokemon/miasmite/
- https://www.smogon.com/forums/threads/cap-28-prevo-final-product.3674225/

**Comment by KrisXV** [comment]
Oh, sorry! I didn't see the update to your commit, so I fixed the build myself.

**Comment by tylerstanczak** [comment]
@KrisXV could you take a look at the first commit in this PR and let me know if this is an appropriate way to solve Punishment for gen 4?

**Comment by AustinXII** [comment]
> @KrisXV could you take a look at the first commit in this PR and let me know if this is an appropriate way to solve Punishment for gen 4?

Looks good! Just gotta remove the duplicate code

**Comment by tylerstanczak** [comment]
I think I removed the commit for fixing master that @KrisXV pushed himself

This is the first time I've contributed to open source, so I'd appreciate it if you have some comments on why removing the duplicate code is important here. From my understanding, if the code is the same, merging the PR wont harm anything. With that in mind, can you teach me what the consequences are for not removing the duplicate code?

**Comment by KrisXV** [comment]
@tylerstanczak If the same code is added by two different people, it can cause a merge conflict, which means we can't really merge your code.

**Comment by tylerstanczak** [comment]
I see...

GitHub is currently saying there are no conflicts:
"This branch has no conflicts with the base branch"

You're able to merge now then, right?

**Comment by AustinXII** [comment]
Yup

**Comment by tylerstanczak** [comment]
Yay I'm helping !

**Pull request merged**
