### PR TITLE
Implement Big Root Interactions with Draining Moves

### LINKED ISSUE #516: Big Root not working in Generation 9 / SV
Big Root isn't working in SV Damage Calc because HP potentially recovered isn't changing.
image

### PR DESCRIPTION
**Pull request by Zrp200**
This should resolve #516.

I added a test for the draining interactions near the other draining interaction tests. I did not add a test for the leech seed interaction, though, since I wasn't sure where it would go.

### CODE REVIEW

**Comment by AustinXII** [comment]
Doesn’t big root also need some work done in the `mechanics` files ?

**Comment by Zrp200** [comment]
> Doesn’t big root also need some work done in the `mechanics` files ?

I don't see where the changes would be made. Big Root multiplies the recovery from Leech Seed and draining moves by 1.3 after the recovery amount is calculated. It doesn't affect the actual damage of any moves.

**Comment by AustinXII** [comment]
Ah I thought it also increased damage of draining moves

**Comment by AustinXII** [comment]
Thanks!

**Pull request merged**
