### PR TITLE
Fix Export

### PR DESCRIPTION
**Pull request by elad-m**
Just changed the '.text()' to '.val()'. 

I guess I should tell you that 3 tests are failing in the data suite. I just cloned, installed, and built it today without any changes and it still fails (so I made this PR anyway). 

These are the tests:
src/test/data.test.ts:34
src/test/data.test.ts:51
src/test/data.test.ts:63

Hope this helps

### CODE REVIEW

**Comment by elad-m** [comment]
Did I do something wrong? Can I do something about it?

**Comment by KrisXV** [comment]
Hey @elad-m, sorry for the delay. I was busy with school until recently, and then I wanted to prioritizing fixing the build error. Can you update your branch to fix the build?

**Comment by elad-m** [comment]
@KrisXV  I figured you were probably busy. Anyway, looks like it works :)

**Comment by KrisXV** [comment]
Hm, it looks like you botched a rebase. Would you mind trying again?

**Pull request closed without merging**
