### PR TITLE
Add support of special properties of GMax moves 

### PR DESCRIPTION
**Pull request by yghdj**
The goal is to implement the special EOT effects caused by various G-Max Moves, namely:
* G-Max Wildfire/Volcalith (1/6 max HP damage), 
* G-Max Finale (1/6 max HP restored), 
* G-Max Sandblast/Centiferno (Sand Tomb/Fire Spin effect).

For now, only the Wildfire effect is implemented, and using G-Max Wildfire doesn't activate it yet.

### CODE REVIEW

**Comment by scheibo** [comment]
Looks good so far! I've marked this as in-progress on the master bug listing our missing Dynamax features. Thanks for taking this on! :)

**Comment by scheibo** [comment]
Hey @yghdj, do you need any help here? :)

**Comment by yghdj** [comment]
Hey, sorry I've been quite busy lately and didn't have much time to wrap this up. I'm having a free day tomorrow so I'll try to work on this.

**Comment by scheibo** [comment]
No rush at all, just wanted to make sure you weren't stuck on something!

**Comment by yghdj** [comment]
I think everything is covered so far, might add another button for Centiferno/SandTomb since those effects continue for 4 turns even if the Pokemon is switched out.

**Comment by scheibo** [comment]
Great! Thanks for taking this on!

**Comment by scheibo** [comment]
FYI: I will deploy these 2 changes tomorrow with the monthly sets update

**Pull request merged**
