### PR TITLE
Modularize the Gen 7 & 8 mechanics page

### PR DESCRIPTION
**Pull request by lighthouse64**
I modularized the functions in this file so that one can individually calculate base power modifiers, attack modifiers, and whatnot.

I also fixed the bug of neuroforce being added to the base power modifiers.

### CODE REVIEW

**Comment by AustinXII** [comment]
Sorry for the late reply! How much testing has been done with this code?

**Comment by lighthouse64** [comment]
I made sure that ``npm test`` passed, and it doesn't seem to cause problems with the client.

**Comment by AustinXII** [comment]
> I made sure that ``npm test`` passed, and it doesn't seem to cause problems with the client.

We don't have full tests. Could you quickly test one of the changed lines to ensure everything works?

**Comment by lighthouse64** [comment]
Sorry, I'm not quite sure what you mean by that.  I just rebased my fork.

**Comment by AustinXII** [comment]
Hmm looks like that rebase didn't do exactly what you wanted, could you fix that?

**Comment by lighthouse64** [comment]
Fixed, the commit shouldn't look messy anymore.

**Comment by AustinXII** [comment]
Thanks!

**Pull request merged**
