### PR TITLE
SV update

### PR DESCRIPTION
**Pull request by AustinXII**

### CODE REVIEW

**Comment by AustinXII** [comment]
Gotta do species and update mechanics

**Comment by ajhyndman** [comment]
Hey @AustinXII!  I'm excited to see this work starting.

I didn't push a PR, because I don't know how you want to coordinate the updates, but here's a bit of code I hacked together to support terastal types specifically, in case you find it useful as a point of reference.

https://github.com/smogon/damage-calc/compare/master...ajhyndman:damage-calc:dev?expand=1

If you would like me to pull anything out of this and submit it as a PR, just let me know!

**Comment by AustinXII** [comment]
@ajhyndman sure if you want to make a PR I will look at that. If I don't get a response in about an hour I will do it myself though

**Comment by ajhyndman** [comment]
@AustinXII Hey!  Sure, assuming I'm not too late, I'll try to extract just the teraType property and associated math.

**Comment by AustinXII** [comment]
@ajhyndman feel free to message me on PS, @Austin I've been on all day, sorry I did species (besides some formes that I just wanna see how they work), just going to do mechanics now

**Comment by ajhyndman** [comment]
Pushed a PR here!  https://github.com/smogon/damage-calc/pull/485

Sure, let me see if I can figure out chatting in Showdown.

**Comment by ajhyndman** [comment]
@AustinXII I poked around on this branch just a little.

At first I had a few exceptions complaining about missing "mods" for gen 9.  Clearing my node_modules and reinstalling fixed that.

Now it looks like it's just a matter of further reconciling the data for each generation.  Does that sound right?  It does look like there are a couple legitimately missing moves and species:

image

**Comment by ajhyndman** [comment]
I noticed that the keys in the species data hadn't been updated to match this repo's style yet, so I pushed a change for that here:

https://github.com/AustinXII/damage-calc/pull/1

I think you should be able to just accept the pull request to add it to your working branch.

**Comment by AustinXII** [comment]
All vs one is borked, will have to look into that, otherwise I think we are pretty much done @ajhyndman

**Comment by ajhyndman** [comment]
Whoah, no way!  Unfortunately I'm busy today and tomorrow, but the rest of the week I'll be very engaged with this.

**Comment by VertigoXY** [comment]
@AustinXII Hi hi, just stumbled upon the update as I wanted to look into it and give a hand but looks like you covered most of it already. All I see missing is replacing Hail with Snow and mechanics that go along with it — I don't know if you were planning on doing it soon, I can look into it otherwise, just let me know!

**Comment by AustinXII** [comment]
Ah yes, I completely forgot about that. Feel free to do it yourself and submit a pr! :)

**Pull request merged**
