### PR TITLE
Add click-to-copy feature

### PR DESCRIPTION
**Pull request by DimK19**
Made a very small addition using the Clipboard API. I ran `npm test` locally, apparently the two failing tests are unrelated to it. Hope it works properly!

### CODE REVIEW

**Comment by KrisXV** [comment]
Hey! Sorry for the delay; could you provide a screenshot of how this looks?

**Comment by DimK19** [comment]
Hello! Here's how it looks currently (my mouse pointer is not showing on the screenshot, but is on the main result sentence and changes to "hand-pointer")
image

Since opening the request, I've thought of making a tooltip pop up after clicking as a confirmation, but it is not ready yet. Also, I noticed the failing tests have been fixed in subsequent pr's, so if you could tell me how to fix them I'll do it here too. Thanks.

**Comment by DimK19** [comment]
I made a mess trying to sync my fork with the latest build, so I just hard reset and made a new commit. Now it is passing all the tests locally.
image
The pop-up tooltip disappears after 2 seconds.

**Comment by AustinXII** [comment]
@DimK19 sorry for the late replies, I will look at this today and get back to you. It looks pretty good at a click glance though!

**Comment by monsanto** [comment]
Seems like useful functionality, hopefully Austin will review it but if it doesn't happen I will.

**Comment by AustinXII** [comment]
Thanks!

**Pull request merged**
